require 'test/unit'
require 'rubygems'
require File.dirname(__FILE__) + '/../lib/to_xls'
require File.dirname(__FILE__) + '/user_model'

class ToXlsTest < Test::Unit::TestCase

  def setup
    @users = []
    @users << User.new(:id => 1, :name => 'Ary', :age => 24, :birth_date => (DateTime.now - (24*365)))
    @users << User.new(:id => 2, :name => 'Nati', :age => 21, :birth_date => (DateTime.now - (21*365)))
  end

  def test_with_empty_array
    assert_equal( "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Workbook xmlns:x=\"urn:schemas-microsoft-com:office:excel\" xmlns:ss=\"urn:schemas-microsoft-com:office:spreadsheet\" xmlns:html=\"http://www.w3.org/TR/REC-html40\" xmlns=\"urn:schemas-microsoft-com:office:spreadsheet\" xmlns:o=\"urn:schemas-microsoft-com:office:office\"><Styles><Style ss:ID=\"Default\" ss:Name=\"Normal\"><Alignment ss:Vertical=\"Bottom\" /><Borders /><Font ss:FontName=\"Arial\" /><Interior /><NumberFormat /><Protection /></Style><Style ss:ID=\"s21\"><Font x:Family=\"Swiss\" ss:Bold=\"1\" /></Style><Style ss:ID=\"s22\"><Font ss:Format=\"General Date\" /></Style></Styles><Worksheet ss:Name=\"Sheet1\"><Table></Table></Worksheet></Workbook>", [].to_xls )
  end
  
  def test_with_no_options
    assert_equal( "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Workbook xmlns:x=\"urn:schemas-microsoft-com:office:excel\" xmlns:ss=\"urn:schemas-microsoft-com:office:spreadsheet\" xmlns:html=\"http://www.w3.org/TR/REC-html40\" xmlns=\"urn:schemas-microsoft-com:office:spreadsheet\" xmlns:o=\"urn:schemas-microsoft-com:office:office\"><Styles><Style ss:ID=\"Default\" ss:Name=\"Normal\"><Alignment ss:Vertical=\"Bottom\" /><Borders /><Font ss:FontName=\"Arial\" /><Interior /><NumberFormat /><Protection /></Style><Style ss:ID=\"s21\"><Font x:Family=\"Swiss\" ss:Bold=\"1\" /></Style><Style ss:ID=\"s22\"><Font ss:Format=\"General Date\" /></Style></Styles><Worksheet ss:Name=\"Sheet1\"><Table><Row><Cell ss:StyleID=\"s21\"><Data ss:Type=\"String\">id</Data></Cell><Cell ss:StyleID=\"s21\"><Data ss:Type=\"String\">name</Data></Cell><Cell ss:StyleID=\"s21\"><Data ss:Type=\"String\">age</Data></Cell><Cell ss:StyleID=\"s21\"><Data ss:Type=\"String\">birth_date</Data></Cell></Row><Row><Cell><Data ss:Type=\"Number\">1</Data></Cell><Cell><Data ss:Type=\"String\">Ary</Data></Cell><Cell><Data ss:Type=\"Number\">24</Data></Cell><Cell ss:StyleID=\"s22\"><Data ss:Type=\"DateTime\">#{@users.first.birth_date.strftime("%Y-%m-%dT%H:%M:%S")}</Data></Cell></Row><Row><Cell><Data ss:Type=\"Number\">2</Data></Cell><Cell><Data ss:Type=\"String\">Nati</Data></Cell><Cell><Data ss:Type=\"Number\">21</Data></Cell><Cell ss:StyleID=\"s22\"><Data ss:Type=\"DateTime\">#{@users.last.birth_date.strftime("%Y-%m-%dT%H:%M:%S")}</Data></Cell></Row></Table></Worksheet></Workbook>", @users.to_xls )
  end
  
  def test_with_no_headers
    assert_equal( "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Workbook xmlns:x=\"urn:schemas-microsoft-com:office:excel\" xmlns:ss=\"urn:schemas-microsoft-com:office:spreadsheet\" xmlns:html=\"http://www.w3.org/TR/REC-html40\" xmlns=\"urn:schemas-microsoft-com:office:spreadsheet\" xmlns:o=\"urn:schemas-microsoft-com:office:office\"><Styles><Style ss:ID=\"Default\" ss:Name=\"Normal\"><Alignment ss:Vertical=\"Bottom\" /><Borders /><Font ss:FontName=\"Arial\" /><Interior /><NumberFormat /><Protection /></Style><Style ss:ID=\"s21\"><Font x:Family=\"Swiss\" ss:Bold=\"1\" /></Style><Style ss:ID=\"s22\"><Font ss:Format=\"General Date\" /></Style></Styles><Worksheet ss:Name=\"Sheet1\"><Table><Row><Cell><Data ss:Type=\"Number\">1</Data></Cell><Cell><Data ss:Type=\"String\">Ary</Data></Cell><Cell><Data ss:Type=\"Number\">24</Data></Cell><Cell ss:StyleID=\"s22\"><Data ss:Type=\"DateTime\">#{@users.first.birth_date.strftime("%Y-%m-%dT%H:%M:%S")}</Data></Cell></Row><Row><Cell><Data ss:Type=\"Number\">2</Data></Cell><Cell><Data ss:Type=\"String\">Nati</Data></Cell><Cell><Data ss:Type=\"Number\">21</Data></Cell><Cell ss:StyleID=\"s22\"><Data ss:Type=\"DateTime\">#{@users.last.birth_date.strftime("%Y-%m-%dT%H:%M:%S")}</Data></Cell></Row></Table></Worksheet></Workbook>", @users.to_xls(:headers => false) )
  end
  
  def test_with_only
    assert_equal( "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Workbook xmlns:x=\"urn:schemas-microsoft-com:office:excel\" xmlns:ss=\"urn:schemas-microsoft-com:office:spreadsheet\" xmlns:html=\"http://www.w3.org/TR/REC-html40\" xmlns=\"urn:schemas-microsoft-com:office:spreadsheet\" xmlns:o=\"urn:schemas-microsoft-com:office:office\"><Styles><Style ss:ID=\"Default\" ss:Name=\"Normal\"><Alignment ss:Vertical=\"Bottom\" /><Borders /><Font ss:FontName=\"Arial\" /><Interior /><NumberFormat /><Protection /></Style><Style ss:ID=\"s21\"><Font x:Family=\"Swiss\" ss:Bold=\"1\" /></Style><Style ss:ID=\"s22\"><Font ss:Format=\"General Date\" /></Style></Styles><Worksheet ss:Name=\"Sheet1\"><Table><Row><Cell ss:StyleID=\"s21\"><Data ss:Type=\"String\">name</Data></Cell></Row><Row><Cell><Data ss:Type=\"String\">Ary</Data></Cell></Row><Row><Cell><Data ss:Type=\"String\">Nati</Data></Cell></Row></Table></Worksheet></Workbook>", @users.to_xls(:only => :name) )
  end
  
  def test_with_empty_only
    assert_equal( "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Workbook xmlns:x=\"urn:schemas-microsoft-com:office:excel\" xmlns:ss=\"urn:schemas-microsoft-com:office:spreadsheet\" xmlns:html=\"http://www.w3.org/TR/REC-html40\" xmlns=\"urn:schemas-microsoft-com:office:spreadsheet\" xmlns:o=\"urn:schemas-microsoft-com:office:office\"><Styles><Style ss:ID=\"Default\" ss:Name=\"Normal\"><Alignment ss:Vertical=\"Bottom\" /><Borders /><Font ss:FontName=\"Arial\" /><Interior /><NumberFormat /><Protection /></Style><Style ss:ID=\"s21\"><Font x:Family=\"Swiss\" ss:Bold=\"1\" /></Style><Style ss:ID=\"s22\"><Font ss:Format=\"General Date\" /></Style></Styles><Worksheet ss:Name=\"Sheet1\"><Table></Table></Worksheet></Workbook>", @users.to_xls(:only => "") )
  end
  
  def test_with_only_and_wrong_column_names
    assert_equal( "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Workbook xmlns:x=\"urn:schemas-microsoft-com:office:excel\" xmlns:ss=\"urn:schemas-microsoft-com:office:spreadsheet\" xmlns:html=\"http://www.w3.org/TR/REC-html40\" xmlns=\"urn:schemas-microsoft-com:office:spreadsheet\" xmlns:o=\"urn:schemas-microsoft-com:office:office\"><Styles><Style ss:ID=\"Default\" ss:Name=\"Normal\"><Alignment ss:Vertical=\"Bottom\" /><Borders /><Font ss:FontName=\"Arial\" /><Interior /><NumberFormat /><Protection /></Style><Style ss:ID=\"s21\"><Font x:Family=\"Swiss\" ss:Bold=\"1\" /></Style><Style ss:ID=\"s22\"><Font ss:Format=\"General Date\" /></Style></Styles><Worksheet ss:Name=\"Sheet1\"><Table><Row><Cell ss:StyleID=\"s21\"><Data ss:Type=\"String\">name</Data></Cell></Row><Row><Cell><Data ss:Type=\"String\">Ary</Data></Cell></Row><Row><Cell><Data ss:Type=\"String\">Nati</Data></Cell></Row></Table></Worksheet></Workbook>", @users.to_xls(:only => [:name, :yoyo]) )
  end
  
  def test_with_except
    assert_equal( "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Workbook xmlns:x=\"urn:schemas-microsoft-com:office:excel\" xmlns:ss=\"urn:schemas-microsoft-com:office:spreadsheet\" xmlns:html=\"http://www.w3.org/TR/REC-html40\" xmlns=\"urn:schemas-microsoft-com:office:spreadsheet\" xmlns:o=\"urn:schemas-microsoft-com:office:office\"><Styles><Style ss:ID=\"Default\" ss:Name=\"Normal\"><Alignment ss:Vertical=\"Bottom\" /><Borders /><Font ss:FontName=\"Arial\" /><Interior /><NumberFormat /><Protection /></Style><Style ss:ID=\"s21\"><Font x:Family=\"Swiss\" ss:Bold=\"1\" /></Style><Style ss:ID=\"s22\"><Font ss:Format=\"General Date\" /></Style></Styles><Worksheet ss:Name=\"Sheet1\"><Table><Row><Cell ss:StyleID=\"s21\"><Data ss:Type=\"String\">age</Data></Cell><Cell ss:StyleID=\"s21\"><Data ss:Type=\"String\">birth_date</Data></Cell></Row><Row><Cell><Data ss:Type=\"Number\">24</Data></Cell><Cell ss:StyleID=\"s22\"><Data ss:Type=\"DateTime\">#{@users.first.birth_date.strftime("%Y-%m-%dT%H:%M:%S")}</Data></Cell></Row><Row><Cell><Data ss:Type=\"Number\">21</Data></Cell><Cell ss:StyleID=\"s22\"><Data ss:Type=\"DateTime\">#{@users.last.birth_date.strftime("%Y-%m-%dT%H:%M:%S")}</Data></Cell></Row></Table></Worksheet></Workbook>", @users.to_xls(:except => [:id, :name]) )
  end
  
  def test_with_except_and_only_should_listen_to_only
    assert_equal( "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Workbook xmlns:x=\"urn:schemas-microsoft-com:office:excel\" xmlns:ss=\"urn:schemas-microsoft-com:office:spreadsheet\" xmlns:html=\"http://www.w3.org/TR/REC-html40\" xmlns=\"urn:schemas-microsoft-com:office:spreadsheet\" xmlns:o=\"urn:schemas-microsoft-com:office:office\"><Styles><Style ss:ID=\"Default\" ss:Name=\"Normal\"><Alignment ss:Vertical=\"Bottom\" /><Borders /><Font ss:FontName=\"Arial\" /><Interior /><NumberFormat /><Protection /></Style><Style ss:ID=\"s21\"><Font x:Family=\"Swiss\" ss:Bold=\"1\" /></Style><Style ss:ID=\"s22\"><Font ss:Format=\"General Date\" /></Style></Styles><Worksheet ss:Name=\"Sheet1\"><Table><Row><Cell ss:StyleID=\"s21\"><Data ss:Type=\"String\">name</Data></Cell></Row><Row><Cell><Data ss:Type=\"String\">Ary</Data></Cell></Row><Row><Cell><Data ss:Type=\"String\">Nati</Data></Cell></Row></Table></Worksheet></Workbook>", @users.to_xls(:except => [:id, :name], :only => :name) )
  end
  
  def test_with_method
    assert_equal( "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Workbook xmlns:x=\"urn:schemas-microsoft-com:office:excel\" xmlns:ss=\"urn:schemas-microsoft-com:office:spreadsheet\" xmlns:html=\"http://www.w3.org/TR/REC-html40\" xmlns=\"urn:schemas-microsoft-com:office:spreadsheet\" xmlns:o=\"urn:schemas-microsoft-com:office:office\"><Styles><Style ss:ID=\"Default\" ss:Name=\"Normal\"><Alignment ss:Vertical=\"Bottom\" /><Borders /><Font ss:FontName=\"Arial\" /><Interior /><NumberFormat /><Protection /></Style><Style ss:ID=\"s21\"><Font x:Family=\"Swiss\" ss:Bold=\"1\" /></Style><Style ss:ID=\"s22\"><Font ss:Format=\"General Date\" /></Style></Styles><Worksheet ss:Name=\"Sheet1\"><Table><Row><Cell ss:StyleID=\"s21\"><Data ss:Type=\"String\">id</Data></Cell><Cell ss:StyleID=\"s21\"><Data ss:Type=\"String\">name</Data></Cell><Cell ss:StyleID=\"s21\"><Data ss:Type=\"String\">age</Data></Cell><Cell ss:StyleID=\"s21\"><Data ss:Type=\"String\">birth_date</Data></Cell><Cell ss:StyleID=\"s21\"><Data ss:Type=\"String\">is_old?</Data></Cell></Row><Row><Cell><Data ss:Type=\"Number\">1</Data></Cell><Cell><Data ss:Type=\"String\">Ary</Data></Cell><Cell><Data ss:Type=\"Number\">24</Data></Cell><Cell ss:StyleID=\"s22\"><Data ss:Type=\"DateTime\">#{@users.first.birth_date.strftime("%Y-%m-%dT%H:%M:%S")}</Data></Cell><Cell><Data ss:Type=\"String\">false</Data></Cell></Row><Row><Cell><Data ss:Type=\"Number\">2</Data></Cell><Cell><Data ss:Type=\"String\">Nati</Data></Cell><Cell><Data ss:Type=\"Number\">21</Data></Cell><Cell ss:StyleID=\"s22\"><Data ss:Type=\"DateTime\">#{@users.last.birth_date.strftime("%Y-%m-%dT%H:%M:%S")}</Data></Cell><Cell><Data ss:Type=\"String\">false</Data></Cell></Row></Table></Worksheet></Workbook>", @users.to_xls(:methods => [:is_old?]) )
  end
  
end
